spring:
  datasource:
    url: jdbc:mariadb://192.168.1.3:3306/pshop
    username: ${DB_USERNAME:apiservice}
    password: ${DB_PASSWORD:wip015ykC1}
    driver-class-name: org.mariadb.jdbc.Driver
    tomcat:
      initial-size: 3
      max-idle: 1
      min-idle: 1
      max-wait: 30000
server:
  port: 9090
